<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $templates = DB::table('contract_templates')->select(['id', 'body'])->get();

        foreach ($templates as $template) {
            $body = (string) $template->body;
            $updated = str_replace('Human Link', '{{company_name}}', $body);
            $updated = str_replace(
                'Generated by {{company_name}}',
                'Generated for {{company_name}}',
                $updated,
            );

            if ($updated === $body) {
                continue;
            }

            DB::table('contract_templates')
                ->where('id', $template->id)
                ->update(['body' => $updated]);
        }
    }

    public function down(): void
    {
        // Irreversible: company-specific names cannot be restored to "Human Link" safely.
    }
};
